parameters: {}
packages:
    - name: sample
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: hello
          binary: false
          main: ""
          runtime: nodejs:18
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: bye
          runtime: nodejs:18
          web: true

environment:
  TEST_STAM: ${STAM}